graph LR
    S1<-->S5
    S1<-->S4

    subgraph S0["Docker Swarm"]
        S1
        S2
        S3
        S4
        S5
        S7
    end
    
    subgraph S1["메인 서버(Nest.js)"]
        A["HTTP 요청 응답"]
        B["Websocket 연결"]
        C["RabbitMQ 메시지 발생 및 Ack 구독"]
    end

    subgraph S3["Log Proccessor(Python)"]
        G["최신 변경사항 저장"]
        J["모든 변경사항 저장"]
        F["변경사항 메시지 구독"]
    end

    subgraph S4["Influx/Redis"]
        H["PLC별 최신 변경사항 저장"]
        K["과거 변경이력 저장"]
        I["유저 토큰 저장"]
        G-->|캐싱|H
        J-->|모든 변경 내용|K
    end

    subgraph S2["RPi(Python)"]
        E["변경사항(센서, 접점, 레지스터) 및 Ack 발행"]
        AA["명령 처리"]
        D["RabbitMQ 명령 메시지 구독"]
        C <-->|직접 연결|D
        D --> AA
        AA --> E
    end

    subgraph S5["Mysql"]
        L["비즈니스 데이터 및 메타데이터 저장"]
    end

    subgraph S6["Client(User)"]
        M["요청"]
        M-->A
        M-->B
    end

    subgraph S7["RabbitMQ"]
        N["메시지 발행 및 구독"]
        C-->N
        E-->|Fan out|N
        F-->N
    end